// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Fri Jan 12 14:29:44 2024

OnChipROM16KWords OnChipROM16KWords_inst
(
	.Clock(Clock_sig) ,	// input  Clock_sig
	.Address(Address_sig) ,	// input [13:0] Address_sig
	.RomSelect_H(RomSelect_H_sig) ,	// input  RomSelect_H_sig
	.DataOut(DataOut_sig) 	// output [15:0] DataOut_sig
);

